POST http://localhost:3000/daily-login-source HTTP/1.1
content-type: application/json

{
    "dayCount": 3,
    "initialQuantity": 300,
    "inventoryId": 1
}

###

POST http://localhost:3000/inventory HTTP/1.1
content-type: application/json

{
    "title": "SkipQuestion Booster"
}


###

GET http://localhost:3000/daily-login-source HTTP/1.1


###

POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "email": "ganesh.a@juegostudio.com"
}


### 
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "email": "saurav.kumar@juegostudio.com",
    "fullName": "Saurav Kumar"
}

### 

GET http://localhost:3000/users/ganesh.a@juegostudio.com HTTP/1.1

###

POST http://localhost:3000/question HTTP/1.1
content-type: application/json

{
    "description": "Who won 2019 Cricket World Cup?",
    "difficulty": "LOW",
    "answers": [{
        "description": "India"
    },{
        "description": "South Africa"
    }]
}